export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A futuristic cityscape at sunset', 
  'A serene beach with unicorns playing volleyball', 
  'A two-story treehouse in the style of Frank Lloyd Wright', 
  'Cybernetic dinosaurs roaming a neon jungle', 
  'A cat made out of watermelon', 
  'A castle floating in the sky', 
  'A steampunk robot making a cup of coffee', 
  'A cubist interpretation of a sunflower', 
  'An alien planet with bioluminescent plants', 
  'A mermaid reading a book under the sea',
  'A gnome village inside a hollow tree', 
  'A mouse piloting a cheese spaceship', 
  'A robot dream', 
  'Picasso rendition of a basketball game', 
  'A garden of musical instruments growing from the ground', 
  'A cityscape made of candy and desserts', 
  'A space station designed by bees', 
  'A dragon knitting a sweater', 
  'A library in a cloud', 
  'A landscape painted with words', 
  'A wolf howling at a moon made of cheese', 
  'A pirate ship sailing in a sea of soda', 
  'A carnival on Mars', 
  'A snowman sunbathing on a hot beach',
  'A bear playing a saxophone in a jazz band',
  'A forest made of candy canes', 
  'A knight riding a giant snail', 
  'An underwater tea party', 
  'A skyscraper made of playing cards', 
  'A cybernetic octopus playing chess',
  'A dinosaur wearing a tuxedo',
  'A tree growing upside-down from a cloud',
  'A ghost cooking breakfast',
  'A superhero with the power of music',
  'A book that opens to a miniature city',
  'A map of a world inside a leaf',
  'An elephant painting a self-portrait',
  'An ancient temple with modern graffiti',
  'A squirrel wearing a suit of armor',
  'An ice cream sundae mountain',
  'A haunted house on wheels',
  'A train traveling through the rings of Saturn',
  'A giraffe wearing a bow tie',
  'A turtle carrying an island on its back',
  'A sunset painted with neon colors',
  'A crow wearing a crown',
  'A moonlit dance of mythical creatures',
  'A robot walking a dog on the moon',
  'A rocket made of crystals launching into the cosmos',
'A martian landscape with a river of stardust',
'A city skyline with a backdrop of interstellar nebula',
'Alien plants growing on the surface of a meteor',
'A space station designed by ancient Egyptians',
'A moonlit picnic on an asteroid',
'Astronauts playing baseball on the Moon',
'A nebula shaped like a phoenix',
'A sea of stars being fished by a cosmic fisherman',
'A galaxy unfolding from an ancient book',
'A constellation in the shape of a dragon',
'Saturns rings made of multicolored candy',
'An alien marketplace bustling with interstellar commerce',
'A symphony orchestra performing on a space station',
'A space whale swimming through a nebula',
'An alien jungle with bioluminescent trees under a double star',
'A robot exploring the ruins of an ancient civilization on Mars',
'A solar system in a glass orb',
'An intergalactic train connecting spiral galaxies',
'Jupiter as seen from its moon Europa',
'A starship made from enchanted wood',
'A lunar base in the style of Art Deco',
'A cosmic dragon curled around a quasar',
'A comet shaped like a soaring bird',
'Planet Earth in a crystal ball held by an astronaut',
'A pulsar serving as a lighthouse for lost starships',
'A black hole as a gate to a fantasy world',
'A nebula being painted by an artist on a floating asteroid',
'A celestial palace floating in the rings of Saturn',
'A group of penguins having a snowball fight',
'A sunset reflected in a mirror maze',
'A ghost playing a piano in an abandoned mansion',
'A carousel made of origami animals',
'A rabbit pulling a magician out of a hat',
'A castle made of soap bubbles',
'A giraffe peeking out of a skyscraper window',
'A fish swimming in a cloud above a desert',
'An orchestra of flowers playing to the rhythm of the wind',
'A turtle carrying a city on its back',
'A tree growing books instead of leaves',
'A dragon and a knight playing a game of chess',
'A steampunk submarine in a bottle',
'A cat painting a self-portrait with yarn',
'An underwater train station',
'A squirrel conducting a symphony of birds',
'An octopus knitting a colorful blanket',
'A ballerina balancing on a crescent moon',
'A bakery inside a giant oven',
'A bicycle race between tortoises and hares',
'An alien zoo with exotic, never-seen animals',
'A snowman sculpting a statue of a child',
'A mouse reading a bedtime story to cheese',
'A lighthouse illuminating a path of music notes',
'A rainbow breaking through a monochrome cityscape',
'A cityscape growing out of a vinyl record',
'A picnic on a floating leaf in a pond',
'The sound of silence visualized',
'An emotion called "Sonder" depicted as a landscape',
'The taste of joy',
'A dreamcatcher catching nightmares',
'The scent of a memory',
'Time melting like a Dali painting',
'A physical representation of déjà vu',
'The color of laughter',
'A sunset painted with the hues of nostalgia',
'Gravity as a visual concept',
'A forest made of whispers',
'The intersection of hope and despair',
'Love depicted as a botanical garden',
'A city built on the concept of solitude',
'Echoes transforming into a mountain range',
'A symphony composed of autumn leaves',
'Music visualized as a stormy sea',
'The weight of a secret illustrated as an object',
'A landscape embodying the emotion of longing',
'The essence of a summer breeze in a visual form',
'An architectural representation of freedom',
'Words dancing in the rhythm of rain',
'The birth of an idea visualized as a sunrise',
'The embodiment of serendipity in a forest scene',
'A constellation of lost dreams',
'The color of time',
'A waterfall made of forgotten memories',
'An ocean woven from threads of thought',
'The rhythm of life depicted as a cityscape',
'The texture of a thought',
'A labyrinth made from echoes of a song',
'An abstract representation of resilience',
'A sunrise made of the first sip of coffee',
'A sculpture of silence in a noisy city',
'An embodiment of curiosity in a surreal landscape',
'A prism refracting a ray of hope',
'A symphony of emotions encapsulated in a still life',
'The tranquility of a morning captured as a landscape',
'A map of unspoken words',
'Kinetic energy visualized as a wild dance',
'A visual interpretation of a lullaby',
'The echoes of past civilizations represented as ruins',
'A melody frozen in time',
'The visualization of a heartbeat as a city',
'The nostalgia of a childhood summer as a beach scene',
'A path carved by words left unsaid',
'The process of metamorphosis represented by a clock',
'A visual representation of the phrase "time heals all wounds"',
'The scent of rain on dry earth represented visually',
'An abstract interpretation of the concept "unity in diversity"',

];